require "./spec_helper"

describe Antenna do
  describe "antinodes" do
    # ..........
    # ...#......
    # ..........
    # ....a.....
    # ..........
    # .....a....
    # ..........
    # ......#...
    # ..........
    # ..........
    it "returns the locations of both antinodes between two Antennas" do
      antenna_1 = Antenna.new('a', Point.new(x: 4, y: 3))
      antenna_2 = Antenna.new('a', Point.new(x: 5, y: 5))
      antenna_1.antinodes(antenna_2).should eq([
        Point.new(x: 3, y: 1),
        Point.new(x: 6, y: 7),
      ])
    end
  end
end
